### ISSUE TITLE
Work out what a musical input looks like

### ISSUE THREAD

**Issue by Aliceravier** [OrganisedAFID/sound-pirates#4]
Figure out what kinds of signal we might get and plan how to deal with them.
Problems may be:
Two notes at once
Things that aren't actually notes like just loud innocuous noises

**Comment by faij2009** [comment]
Analysed audio from @IsabellaSheldon 's clarinet. Different frequency peaks seen with different notes played.

Still to analysis what 2 notes at once looks like
